app.id=102324206
app.token=unrReqhZMjRCLVCzMqReHjOic8WgOUkL
app.secret=P0cErU8mR6mTAsaJ2mWH2oaNBzodTJA1

nav.version=2601
user.url=https://bot.flyatcsim.club/GetUserData.php
online.url=https://bot.flyatcsim.club/Whazzup.php
